### ISSUE TITLE
Parser Error in STEPn macro

### ISSUE THREAD

**Issue by bernhardFRG** [jakkos-net/whilers#10]
Hi Jak,

I hope this is the right medium to report the bugs I observe :-).
When I want to run the self-interpreter u.while (see my Canvas Limits page) there is an issue with parsing STEPn:

Failed to parse src file in tab 1!
failed to parse program:
0: at line 33, in Tag:
    } else
      ^

But hwhile parses it correctly. Note that I simply dragged the file that runs in hwhile into whilers here.
(BTW does 0: mean at position 0 of line 33?)
Cheers,
  Bernhard

**Comment by jakkos-net** [comment]
Should be fixed on live version, you can close the issue once you confirm it works :)
