### ISSUE TITLE
Syntax highlighting in dark v light mode

### ISSUE THREAD

**Issue by bernhardFRG** [jakkos-net/whilers#11]
Hi Jak,

I noticed (in light mode) the colour scheme is not so great (even it is from the student from previous years). I think this was mainly for dark mode.
In light mode, the :=, = and true and false literals are hard to read.
On the other hand in dark mode the keyword prog, all program variables and braces are hard to read.
 I think we need different palettes for both modes. Could this be done easily?

I'd suggest:

Dark mode changes:
white colour for the variables  and prog in dark mode, yellow or white colour for {}

Light mode changes:
Brown colour for = and :=.

Both modes:
all literals whether numbers or booleans should be purple.

Cheers,
  Bernhard

**Comment by jakkos-net** [comment]
I've forced light-mode-only on the live version and updated the colors for =/:= and literals. Close the issue if this fixes the problem, otherwise I can make more changes :)
