### ISSUE TITLE
Output window not resizable

### ISSUE THREAD

**Issue by bernhardFRG** [jakkos-net/whilers#12]
Hi Jak,

not really a big "issue" but it hampers usage of the compilation features:

the output window can not be resized. If I output a larger program I cannot properly read it. I need to select-all and copy it into another window.  So another idea would be to open those converted programs directly in a new *editor* window but then, for the programs as data outputs,  you'd need a different type of window that is not automatically parsed (as it would block running any programs due to it not being while syntax).

Cheers,
  Bernhard

**Comment by jakkos-net** [comment]
I've changed the live version to have the output window to expand to fit its contents and have the whole page be scrollable. If this fixes the problem, close the issue, otherwise we can discuss other solutions :)
