### ISSUE TITLE
Another program that does not parse

### ISSUE THREAD

**Issue by bernhardFRG** [jakkos-net/whilers#14]
Hi Jak,

the following program (which you can use as reference for syntax highlighting as it should contain all features) does NOT parse in whilers (but runs fine in hwhile):
[reference.txt](https://github.com/jakkos-net/whilers/files/14359699/reference.txt)
Note that I had to change the extensions from .while to .txt so that GitHub was happy :-).

The given error in whilers is:

Failed to parse src file in tab 5!
failed to parse program:
0: at line 19, in Tag:
 Z:= cons hd hd hd X cons Y nil;
                               ^
Cheers,
  Bernhard

**Comment by jakkos-net** [comment]
Should be fixed on live version, you can close the issue once you confirm it works :)
